[build]
  command   = "npm run build"
  functions = "out_functions"
  publish   = "out_publish"
[build.environment]
  YARN_VERSION = "1.22.5"

[dev]
  functions = "out_functions"
  publish   = "out_publish"
  framework = "#static"

[[plugins]]
  package = "netlify-plugin-cache-nextjs"